server {
    listen 80;
    server_name abert.homelinuxserver.org;

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name abert.homelinuxserver.org;

    ssl_certificate /etc/nginx/certs/live/abert.homelinuxserver.org/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/live/abert.homelinuxserver.org/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html
    }
}
