
services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.1
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=Oslo
      - TZ=Europe/Oslo
    volumes:
      - ./gluetun/config:/gluetun
    ports:
      - 8081:8080   # qBittorrent web-UI (legges her, ikke på qBit)
    restart: unless-stopped
