
services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.1
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=Oslo
      - TZ=Europe/Oslo
    ports:
      - 8081:8080   # qBittorrent web-UI
    restart: unless-stopped

  qbittorrent:
      image: linuxserver/qbittorrent:5.1.4-r3-ls452
      container_name: qbittorrent
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Oslo
        - WEBUI_PORT=8080
      volumes:
        - /opt/homeserver/qbittorrent:/config
        - /mnt/storage/media:/downloads
      network_mode: "service:gluetun"
      depends_on:
        - gluetun
      restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:2.3.5.5327-ls144
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /opt/homeserver/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:4.0.17.2952-ls310
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /opt/homeserver/sonarr:/config
      - /mnt/storage/media:/media
      - /mnt/storage/media:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:6.1.1.10360-ls300
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /opt/homeserver/radarr:/config
      - /mnt/storage/media:/media
      - /mnt/storage/media:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr:3.1.0.4875-ls26
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /opt/homeserver/lidarr:/config
      - /mnt/storage/media:/media
      - /mnt/storage/media:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:10.11.8ubu2404-ls30
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /opt/homeserver/jellyfin:/config
      - /mnt/storage/media:/media:ro
    ports:
      - 8096:8096
    restart: unless-stopped
