
include:
  - ./enshrouded/docker-compose.yml
  - ./nginx/docker-compose.yml
  - ./terraria/docker-compose.yml
  - ./fileshare/docker-compose.yml

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2026.02.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Oslo'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: 'all'
    cap_add:
      - NET_ADMIN
    networks:
      homeserver_default:
        ipv4_address: 172.18.0.5
    restart: unless-stopped

  wireguard:
    image: linuxserver/wireguard:1.0.20250521
    container_name: wireguard
    cap_add:
     - NET_ADMIN
     - SYS_MODULE
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=Europe/Oslo
     - SERVERURL=auto
     - SERVERPORT=51820
     - PEERS=3
     - PEERDNS=172.18.0.5
     - INTERNAL_SUBNET=10.13.13.0 
     - ALLOWEDIPS=0.0.0.0/0
    volumes:
     - ~/wireguard/config:/config
     - /lib/modules:/lib/modules:ro
    ports:
     - "51820:51820/udp"
    sysctls: 
     - net.ipv4.conf.all.src_valid_mark=1
    networks:
     - homeserver_default
    restart: unless-stopped

networks:
  homeserver_default:
    external: true

