
services:
  samba:
    image: dockurr/samba:4.23.5
    container_name: samba
    environment:
      NAME: "data"
      USER: "${fileshare_username}"
      PASS: "${fileshare_password}"
    ports: 
      - "445:445"
    volumes:
      - /mnt/storage/reaper:/storage/reaper
    restart: unless-stopped

