[global]
ntlm auth = yes
idmap config * : backend = tdb
idmap config * : range = 1000-9999
workgroup = WORKGROUP
security = user
server min protocol = SMB2
passdb backend = tdbsam
load printers = no
printing = bsd
printcap name = /dev/null
disable spoolss = yes
force user = benjamin
force group = benjamin

[reaper]
path = /storage/reaper
valid users = benjamin 
read only = no
browsable = yes

[sounds]
path = /storage/sounds
valid users = benjamin  
read only = no
browsable = yes
