name: Provision VMs

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - terraform/**
      - .github/workflows/terraform.yml

  pull_request:
    paths:
      - terraform/**
      - .github/workflows/terraform.yml

concurrency:
  group: terraform
  cancel-in-progress: false

defaults:
  run:
    working-directory: ./terraform

jobs:
  terraform:
    runs-on: [self-hosted, debian]
    steps:
      - uses: actions/checkout@v7
        with:
          clean: true

      - uses: hashicorp/setup-terraform@v4

      - name: Format check
        run: terraform fmt -check -diff -recursive

      - name: Init
        run: terraform init -input=false

      - name: Validate
        run: terraform validate

      - name: Plan (PR)
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false -no-color

      - name: Apply
        if: github.event_name != 'pull_request'
        run: terraform apply -input=false -auto-approve

