name: Deploy to server

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, debian]
    steps:
      - uses: actions/checkout@v6
        with:
          clean: true

      - name: Decrypt secret
        run: sops -d --input-type dotenv --output-type dotenv .env.enc > .env

      - name: Decrypt secret
        working-directory: ./enshrouded
        run: sops -d --input-type dotenv --output-type dotenv .env.enc > .env

      - name: Decrypt secret
        working-directory: ./fileshare
        run: sops -d --input-type dotenv --output-type dotenv .env.enc > .env

      - name: Deploy
        run: |
          docker compose up -d --pull always --remove-orphans
          docker system prune -f
