name: Deploy to server

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, debian]
    steps:
      - uses: actions/checkout@v7
        with:
          clean: true

      - name: Decrypt secret
        run: "$GITHUB_WORKSPACE/.github/scripts/decrypt-sops-env.sh"

      - name: Decrypt secret
        working-directory: ./enshrouded
        run: "$GITHUB_WORKSPACE/.github/scripts/decrypt-sops-env.sh"

      - name: Decrypt secret
        working-directory: ./fileshare
        run: "$GITHUB_WORKSPACE/.github/scripts/decrypt-sops-env.sh"

      - name: Decrypt secret
        working-directory: ./mediaserver
        run: "$GITHUB_WORKSPACE/.github/scripts/decrypt-sops-env.sh"

      - name: Decrypt secret
        working-directory: ./runescape-dragonwilds
        run: "$GITHUB_WORKSPACE/.github/scripts/decrypt-sops-env.sh"

      - name: Deploy
        env:
          COMPOSE_PROFILES: core,games,https,mediaserver
        run: |
          docker compose up -d --pull always --remove-orphans
          docker system prune -f

