name: Deploy to server

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, debian]
    steps:
      - uses: actions/checkout@v7
        with:
          clean: true

      - name: Decrypt secret
        run: |
          while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" == \#* ]] && continue
            echo "::add-mask::$value"
            echo "$key=$value" >> "$GITHUB_ENV"
          done < <(sops -d .env)

      - name: Decrypt secret
        working-directory: ./enshrouded
        run: |
          while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" == \#* ]] && continue
            echo "::add-mask::$value"
            echo "$key=$value" >> "$GITHUB_ENV"
          done < <(sops -d .env)

      - name: Decrypt secret
        working-directory: ./fileshare
        run: |
          while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" == \#* ]] && continue
            echo "::add-mask::$value"
            echo "$key=$value" >> "$GITHUB_ENV"
          done < <(sops -d .env)

      - name: Decrypt secret
        working-directory: ./mediaserver
        run: |
          while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" == \#* ]] && continue
            echo "::add-mask::$value"
            echo "$key=$value" >> "$GITHUB_ENV"
          done < <(sops -d .env)

      - name: Decrypt secret
        working-directory: ./runescape-dragonwilds
        run: |
          while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" == \#* ]] && continue
            echo "::add-mask::$value"
            echo "$key=$value" >> "$GITHUB_ENV"
          done < <(sops -d .env)

      - name: Deploy
        env:
          COMPOSE_PROFILES: core,games,https,mediaserver
        run: |
          docker compose up -d --pull always --remove-orphans
          docker system prune -f

